export const verifiedFemaleGifUrls: Record<string, string> = {
  "abdominal infra": "https://drive.usercontent.google.com/download?id=1M5L3RQQ-lHFvhr4MQKDmstaM-doMj3nf&export=download&confirm=t",
  "abdominal no banco declinado": "https://drive.usercontent.google.com/download?id=1tJkd9EeRqsxp1ZKsh7T5BxbGWvS4g28d&export=download&confirm=t",
  "abdominal obliquo": "https://drive.usercontent.google.com/download?id=1oFWrBjrkNfb_3wSMKILlfsWH4gqHQi7f&export=download&confirm=t",
  "abdominal supra": "https://drive.usercontent.google.com/download?id=1tJkd9EeRqsxp1ZKsh7T5BxbGWvS4g28d&export=download&confirm=t",
  "afundo com halteres": "https://drive.usercontent.google.com/download?id=1DqZr5qycOBgWK2yjMmvLDFn9QfsAsCEA&export=download&confirm=t",
  "agachamento frontal com barra": "https://drive.usercontent.google.com/download?id=1RpCJyUNMHSGRIJsRbtsB1M4OsbhLlflY&export=download&confirm=t",
  "agachamento goblet com halter": "https://drive.usercontent.google.com/download?id=1Gg8g8P2SJ42_URybvhQsvoAsGy6S8bZZ&export=download&confirm=t",
  "agachamento sumo": "https://drive.usercontent.google.com/download?id=1kRha3M7tDvdiHpgE6ZPB3mU2QHRlpBqa&export=download&confirm=t",
  "bicicleta ergometrica": "https://drive.usercontent.google.com/download?id=1tURi0Nx6-Ql30ZFdGCx3KPVXTMJwiCDv&export=download&confirm=t",
  "bom dia com barra": "https://drive.usercontent.google.com/download?id=1e4HNbb6JQP4eB-HvUEDFop_lB7VihIR5&export=download&confirm=t",
  "coice na maquina": "https://drive.usercontent.google.com/download?id=1QmB566ZNVfIZjR5wXeFqEjnCeqjZAcMo&export=download&confirm=t",
  "crucifixo com halteres": "https://drive.usercontent.google.com/download?id=1VKE5_zMeSY17U1Tt8Dfzz_Vu_-RmDZW8&export=download&confirm=t",
  "crucifixo inverso": "https://drive.usercontent.google.com/download?id=1wHq7KVOt0q4vrHxBtlQQRIs76l9NsbwO&export=download&confirm=t",
  "crucifixo na polia baixa": "https://drive.usercontent.google.com/download?id=1opIMcSadCR9NZaYq5ZVAS6tZaBsFLaUh&export=download&confirm=t",
  "desenvolvimento com halteres": "https://drive.usercontent.google.com/download?id=1Oamx_9L5Vi4tsmBJKOwIzQ0J7_IiLXAs&export=download&confirm=t",
  "elevacao de pernas": "https://drive.usercontent.google.com/download?id=1_j6a6TcCPJlw3eN6kwgaqDDQPglwJOT1&export=download&confirm=t",
  "elevacao frontal": "https://drive.usercontent.google.com/download?id=1xm_AR3RhLCDGqMlZAy9xU1fk5eJZbs5p&export=download&confirm=t",
  "elevacao frontal com anilha": "https://drive.usercontent.google.com/download?id=1bWrqGQJxOzw8AYG3UcTUU_8wO1atsGsi&export=download&confirm=t",
  "elevacao lateral": "https://drive.usercontent.google.com/download?id=1Q4GRe6O4EKQq7SzkOKvDLDWDY3t5HbI_&export=download&confirm=t",
  "elevacao lateral na polia": "https://drive.usercontent.google.com/download?id=1CyC5l7_Yul5vg5C2fePAGZvoMmL73R8Y&export=download&confirm=t",
  "encolhimento com halteres": "https://drive.usercontent.google.com/download?id=1uZvW_-5BhBMgDLC86BhxMUvLUDcL6SFt&export=download&confirm=t",
  "escada ergometrica": "https://drive.usercontent.google.com/download?id=1TgrCpBCS-XjOW0Qu-vsDG4c6R_A6OkYw&export=download&confirm=t",
  "esteira": "https://drive.usercontent.google.com/download?id=1cKgBdKfWXTskX0AhfsWfANxc0kx7KYYP&export=download&confirm=t",
  "farmer walk": "https://drive.usercontent.google.com/download?id=1KgdR8A8lB34Cvdk_ltnYtKMvjyTXVNUD&export=download&confirm=t",
  "gluteo na polia": "https://drive.usercontent.google.com/download?id=1mLAfjz50LukfMSdI64zZ1ND2NXjWL4sh&export=download&confirm=t",
  "graviton barra assistida": "https://drive.usercontent.google.com/download?id=1_ABWfNp0WdMZ6b8DBd-WHzkxjZaBWPcN&export=download&confirm=t",
  "hack squat": "https://drive.usercontent.google.com/download?id=1Jfj2dx_FhEAuvBxaJsWeyrenANaY8AD4&export=download&confirm=t",
  "hip thrust": "https://drive.usercontent.google.com/download?id=1qzWAHHXJj32jPXQQt03KFZQELrL-pTUh&export=download&confirm=t",
  "leg press 45°": "https://drive.usercontent.google.com/download?id=1Yq6sh731TA9h-coZG2s-QxXlAjFT4i-I&export=download&confirm=t",
  "levantamento terra com barra": "https://drive.usercontent.google.com/download?id=1IEzwucrO1ypYdelJ_WXiy8NrKG83rd9w&export=download&confirm=t",
  "levantamento terra romeno": "https://drive.usercontent.google.com/download?id=1evvMOr_8_se0qGOKK2pcqnmh6XKw-TcM&export=download&confirm=t",
  "levantamento terra sumo com barra": "https://drive.usercontent.google.com/download?id=1kOg3BGtUX7c3cCoZJ5ooi9odmdY7GbVe&export=download&confirm=t",
  "mergulho nas paralelas": "https://drive.usercontent.google.com/download?id=1tn1-yzJg6Y7akWI0RQnZJTGeU-lAIb5d&export=download&confirm=t",
  "panturrilha em pe": "https://drive.usercontent.google.com/download?id=1oNIzdE-w35k5KkAKKyue3XtyZcwsagpB&export=download&confirm=t",
  "panturrilha no leg press": "https://drive.usercontent.google.com/download?id=1tPXzwX9JVQs_lI446QCE6jfJtCD_C0FB&export=download&confirm=t",
  "panturrilha no smith": "https://drive.usercontent.google.com/download?id=1hPWRDK0RoUGaV46iTySfFwVFe-eTQgMX&export=download&confirm=t",
  "passada no smith": "https://drive.usercontent.google.com/download?id=1SF4QvnNzgOAwwMwyfipFvAir3siFVacx&export=download&confirm=t",
  "remada alta na polia": "https://drive.usercontent.google.com/download?id=135FVWHBZWCaNMcvzGL7x3RwarsPtsNLc&export=download&confirm=t",
  "remada baixa": "https://drive.usercontent.google.com/download?id=1-pNPs1QWs9dcWznjLVjDC-BiPowXfRUz&export=download&confirm=t",
  "remada curvada com barra": "https://drive.usercontent.google.com/download?id=1K0h1jwWznAaU0dk0W3nh0L9lQsNOy98f&export=download&confirm=t",
  "remada unilateral com halter": "https://drive.usercontent.google.com/download?id=1tEiH2csIVNor5unifBkRFt6k28Vg5JSA&export=download&confirm=t",
  "remo ergometrico": "https://drive.usercontent.google.com/download?id=1l6iBM7cXnfszoRMvg_QWkyFqjQ4_zCoc&export=download&confirm=t",
  "rosca 21": "https://drive.usercontent.google.com/download?id=1rl7woNEiGKv6tFmt01MR5VFjjKFB8e9N&export=download&confirm=t",
  "rosca alternada com halteres": "https://drive.usercontent.google.com/download?id=1WJyLXNE0XzU7ugJtmb4evRiWY0aICcnf&export=download&confirm=t",
  "rosca concentrada": "https://drive.usercontent.google.com/download?id=1XPrSOuVXvymdzsQxtLZ2oeesbIfRswNt&export=download&confirm=t",
  "rosca direta com barra": "https://drive.usercontent.google.com/download?id=1rl7woNEiGKv6tFmt01MR5VFjjKFB8e9N&export=download&confirm=t",
  "rosca inversa com barra": "https://drive.usercontent.google.com/download?id=1hZ2n2KiAVVSBMugthGHr-ez4rY5ipy7T&export=download&confirm=t",
  "rosca na polia": "https://drive.usercontent.google.com/download?id=1rHQOYhBHPjozc5OoAyKYRhgO8FcADLM-&export=download&confirm=t",
  "rosca scott": "https://drive.usercontent.google.com/download?id=1c3FTQIri8otvYqzoDZLgKbx9LYWiAgEN&export=download&confirm=t",
  "step-up com halteres": "https://drive.usercontent.google.com/download?id=13mytdfdtpPGN06gT_77ljxEb62XetljR&export=download&confirm=t",
  "supino declinado com barra": "https://drive.usercontent.google.com/download?id=16ST5gEEm0jC-TVsIRoGGe4qydKUhrmUL&export=download&confirm=t",
  "supino fechado com barra": "https://drive.usercontent.google.com/download?id=17-j4hVUWzxntOV-TBRAgdHIMWQnvipuZ&export=download&confirm=t",
  "supino reto com barra": "https://drive.usercontent.google.com/download?id=1B5w3919f20qo0gDarihzlkLXQGxPvC2Z&export=download&confirm=t",
  "triceps acima da cabeca na polia": "https://drive.usercontent.google.com/download?id=1g8_GioNVPqW_Y0UXRVg29bAnH_43Eho5&export=download&confirm=t",
  "triceps coice": "https://drive.usercontent.google.com/download?id=1g7u8uQ-iLau0KDKt0qt3wSPKuNJ7wJAO&export=download&confirm=t",
  "triceps corda": "https://drive.usercontent.google.com/download?id=13LYDVKuyYfcK9QRgQ81v-volkDohN6b_&export=download&confirm=t",
  "triceps na maquina": "https://drive.usercontent.google.com/download?id=1RjS8p0IsxvU4p0_GRbIN9P16riC6XJXe&export=download&confirm=t",
  "triceps unilateral na polia": "https://drive.usercontent.google.com/download?id=1_VVzWe219-mynK_TZdffEnnCmJbaEl60&export=download&confirm=t",
};

